"""bounded immutable raw upload storage

Revision ID: 7c8ecbbfe69e
Revises: 48b57ba1bfea
"""

import sqlalchemy as sa
from alembic import op

revision = "7c8ecbbfe69e"
down_revision = "48b57ba1bfea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_uploads",
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.CheckConstraint(
            "size_bytes > 0 AND size_bytes <= 10485760", name=op.f("ck_raw_uploads_size")
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name=op.f("fk_raw_uploads_dataset_id_datasets")
        ),
        sa.PrimaryKeyConstraint("dataset_id", name=op.f("pk_raw_uploads")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raw_uploads")
    # ### end Alembic commands ###
