"""initial metadata and local sessions

Revision ID: a0ae31772253
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "a0ae31772253"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("auth_subject", sa.String(length=200), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("auth_subject", name=op.f("uq_users_auth_subject")),
    )
    op.create_table(
        "audit_events",
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_events_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_table(
        "idempotency_records",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("route", sa.String(length=120), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_idempotency_records_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("owner_id", "route", "key", name=op.f("pk_idempotency_records")),
    )
    op.create_index(
        op.f("ix_idempotency_records_expires_at"),
        "idempotency_records",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "login_tickets",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_login_tickets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_login_tickets")),
    )
    op.create_index(
        op.f("ix_login_tickets_expires_at"), "login_tickets", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_login_tickets_user_id"), "login_tickets", ["user_id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_projects_nonempty_name")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)
    op.create_table(
        "web_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_web_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_web_sessions")),
    )
    op.create_index(
        op.f("ix_web_sessions_expires_at"), "web_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_web_sessions_user_id"), "web_sessions", ["user_id"], unique=False)
    op.create_table(
        "datasets",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("raw_key", sa.String(length=500), nullable=False),
        sa.Column("raw_sha256", sa.String(length=64), nullable=False),
        sa.Column("format", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("format IN ('csv','sqlite')", name=op.f("ck_datasets_format")),
        sa.CheckConstraint(
            "status IN ('uploading','validating','ready','rejected','deleting','deleted')",
            name=op.f("ck_datasets_status"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_datasets_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasets")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_datasets_id")),
        sa.UniqueConstraint("raw_key", name=op.f("uq_datasets_raw_key")),
    )
    op.create_index(op.f("ix_datasets_project_id"), "datasets", ["project_id"], unique=False)
    op.create_table(
        "outbox",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("topic", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("retry_count >= 0", name=op.f("ck_outbox_nonnegative_retries")),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_outbox_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
    )
    op.create_index(op.f("ix_outbox_project_id"), "outbox", ["project_id"], unique=False)
    op.create_table(
        "dataset_versions",
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("selection", sa.JSON(), nullable=False),
        sa.Column("schema_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id", "project_id"],
            ["datasets.id", "datasets.project_id"],
            name=op.f("fk_dataset_versions_dataset_id_datasets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_versions")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_dataset_versions_id")),
    )
    op.create_index(
        op.f("ix_dataset_versions_project_id"), "dataset_versions", ["project_id"], unique=False
    )
    op.create_table(
        "runs",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("budget", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=True),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("cancellation_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued','running','awaiting_input','succeeded',"
            "'succeeded_with_warnings','failed','cancelling','cancelled')",
            name=op.f("ck_runs_status"),
        ),
        sa.CheckConstraint("generation > 0", name=op.f("ck_runs_positive_generation")),
        sa.ForeignKeyConstraint(
            ["dataset_version_id", "project_id"],
            ["dataset_versions.id", "dataset_versions.project_id"],
            name=op.f("fk_runs_dataset_version_id_dataset_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_runs_id")),
    )
    op.create_index(op.f("ix_runs_project_id"), "runs", ["project_id"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("private_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_state", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "deletion_state IN ('active','deleting','deleted')",
            name=op.f("ck_artifacts_deletion_state"),
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_artifacts_nonnegative_size")),
        sa.ForeignKeyConstraint(
            ["run_id", "project_id"],
            ["runs.id", "runs.project_id"],
            name=op.f("fk_artifacts_run_id_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint("id", "run_id", name=op.f("uq_artifacts_id")),
        sa.UniqueConstraint("private_key", name=op.f("uq_artifacts_private_key")),
    )
    op.create_index(op.f("ix_artifacts_project_id"), "artifacts", ["project_id"], unique=False)
    op.create_table(
        "pending_questions",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_pending_questions_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pending_questions")),
    )
    op.create_index(
        op.f("ix_pending_questions_run_id"), "pending_questions", ["run_id"], unique=False
    )
    op.create_table(
        "run_events",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_run_events_positive_sequence")),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs")),
        sa.PrimaryKeyConstraint("run_id", "sequence", name=op.f("pk_run_events")),
    )
    op.create_table(
        "stage_attempts",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("runtime_id", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','running','succeeded','failed','cancelled')",
            name=op.f("ck_stage_attempts_status"),
        ),
        sa.CheckConstraint("attempt_number > 0", name=op.f("ck_stage_attempts_positive_attempt")),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_stage_attempts_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_attempts")),
        sa.UniqueConstraint(
            "run_id", "stage", "attempt_number", name=op.f("uq_stage_attempts_run_id")
        ),
    )
    op.create_index(op.f("ix_stage_attempts_run_id"), "stage_attempts", ["run_id"], unique=False)
    op.create_table(
        "dashboards",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("spec_artifact_id", sa.String(length=36), nullable=False),
        sa.Column("bundle_artifact_id", sa.String(length=36), nullable=True),
        sa.Column("render_mode", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "render_mode IN ('generated','fallback')", name=op.f("ck_dashboards_render_mode")
        ),
        sa.ForeignKeyConstraint(
            ["bundle_artifact_id", "run_id"],
            ["artifacts.id", "artifacts.run_id"],
            name=op.f("fk_dashboards_bundle_artifact_id_artifacts"),
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_dashboards_run_id_runs")),
        sa.ForeignKeyConstraint(
            ["spec_artifact_id", "run_id"],
            ["artifacts.id", "artifacts.run_id"],
            name=op.f("fk_dashboards_spec_artifact_id_artifacts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboards")),
        sa.UniqueConstraint("run_id", name=op.f("uq_dashboards_run_id")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dashboards")
    op.drop_index(op.f("ix_stage_attempts_run_id"), table_name="stage_attempts")
    op.drop_table("stage_attempts")
    op.drop_table("run_events")
    op.drop_index(op.f("ix_pending_questions_run_id"), table_name="pending_questions")
    op.drop_table("pending_questions")
    op.drop_index(op.f("ix_artifacts_project_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_runs_project_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_dataset_versions_project_id"), table_name="dataset_versions")
    op.drop_table("dataset_versions")
    op.drop_index(op.f("ix_outbox_project_id"), table_name="outbox")
    op.drop_table("outbox")
    op.drop_index(op.f("ix_datasets_project_id"), table_name="datasets")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_web_sessions_user_id"), table_name="web_sessions")
    op.drop_index(op.f("ix_web_sessions_expires_at"), table_name="web_sessions")
    op.drop_table("web_sessions")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_login_tickets_user_id"), table_name="login_tickets")
    op.drop_index(op.f("ix_login_tickets_expires_at"), table_name="login_tickets")
    op.drop_table("login_tickets")
    op.drop_index(op.f("ix_idempotency_records_expires_at"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("users")
    # ### end Alembic commands ###
