"""configurable inspection and table choice

Revision ID: ca79f5d67de3
Revises: ff09fd7a653b
"""

import sqlalchemy as sa
from alembic import op

revision = "ca79f5d67de3"
down_revision = "ff09fd7a653b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inspections", sa.Column("delimiter_override", sa.String(length=1), nullable=True)
    )
    op.add_column(
        "inspections", sa.Column("revisions", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column("inspections", sa.Column("selected_table", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inspections", "selected_table")
    op.drop_column("inspections", "revisions")
    op.drop_column("inspections", "delimiter_override")
    # ### end Alembic commands ###
